attention_resolutions: 32,16,8
channel_mult: ''
class_cond: true
classifier_attention_resolutions: 32,16,8
classifier_depth: 2
classifier_path: /Project/256x256_classifier.pt
classifier_pool: attention
classifier_resblock_updown: true
classifier_scale: 1.0
classifier_use_fp16: false
classifier_use_scale_shift_norm: true
classifier_width: 128
clip_denoised: true
data:
  eval:
    lama_inet256_ev2li_n100_test:
      batch_size: 1
      class_cond: false
      deterministic: true
      drop_last: false
      ds_conf:
        name: random_ev2li_256
      gt_path: /Project/results/without_BAR
      image_size: 256
      mask_loader: true
      mask_path: /Project/results/boundary_mask
      max_len: 1000
      paths:
        gt_keep_masks: ./log/test_inet256_ev2li/gt_keep_mask
        gts: ./log/test_inet256_ev2li/gt
        lrs: ./log/test_inet256_ev2li/gt_masked
        srs: ./log/test_inet256_ev2li/sr
      random_crop: false
      random_flip: false
      return_dataloader: true
      return_dict: true
diffusion_steps: 1000
dropout: 0.0
image_size: 256
inpa_inj_sched_prev: true
inpa_inj_sched_prev_cumnoise: false
learn_sigma: true
lr_kernel_n_std: 2
model_path: /Project/256x256_diffusion.pt
n_jobs: 25
name: test_inet256_ev2li
noise_schedule: linear
num_channels: 256
num_head_channels: 64
num_heads: 4
num_heads_upsample: -1
num_res_blocks: 2
num_samples: 1
predict_xstart: false
print_estimated_vars: true
resblock_updown: true
rescale_learned_sigmas: false
rescale_timesteps: false
schedule_jump_params:
  jump_length: 500
  jump_n_sample: 2
  n_sample: 1
  t_T: 250
show_progress: true
timestep_respacing: '250'
use_checkpoint: false
use_ddim: false
use_fp16: true
use_kl: false
use_new_attention_order: false
use_scale_shift_norm: true
